FROM node:18

# System packages
RUN apt update && apt install -y yt-dlp ffmpeg \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# App folder
WORKDIR /app

# Dependencies
COPY package*.json ./
RUN npm install --omit=dev

# App source
COPY . .

# Start bot
CMD ["node", "src/main.js"]
